name: Vercel Preview Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  pull_request:
    branches:
      - "main"

jobs:
  Deploy-Preview:
    runs-on: ubuntu-latest
    outputs:
      vercel-url: ${{ steps.deploy.outputs.url }}

    steps:
      - uses: actions/checkout@v4
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        id: deploy
        # run: echo "url=url::$(vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }} | jq -r '.url')"
        run: echo "url=$(vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }} | jq -r '.url')" >> "$GITHUB_OUTPUT"

      - name: Comment on PR
        uses: actions/github-script@v7
        with:
          script: return "Hello!"
          result-encoding: string
      - name: Get result
        run: echo "${{steps.deploy.outputs.url}}"
